FROM mongo:8.0.12

# Config + init scripts
COPY mongo/mongod.dev.conf /etc/mongod.conf
COPY mongo/init /docker-entrypoint-initdb.d

# Keyfile (must be owned by uid 999 and 400/600 perms in the container)
COPY secrets/mongo-keyfile /etc/mongo-keyfile/keyfile
RUN chown 999:999 /etc/mongo-keyfile/keyfile && chmod 400 /etc/mongo-keyfile/keyfile

CMD ["--config", "/etc/mongod.conf"]
