name: mongo-dev
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${MONGODB_CONTAINER_NAME}
    # restart: unless-stopped
    ports:
      - '${MONGO_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    command: ['--config', '/etc/mongod.conf']
    volumes:
      - mongo_data_dev:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  mongo_data_dev:
